# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1533f1b8528677d40965944eeb9c96049247b65ce3bec25362db2eba815cca00707f7b30ae57eeff7f874f41f8998167ec4280c43d692ec9e406b5624a489561

test:
  secret_key_base: 802d9f615d4f09e7eb2a65f7d76adea8aefd0ffd1aa6ade597f8df6a37d54a7056336ad6b51262c43b207238a62df497a15976ef6b24bd01eda4fdc6f5a3b1df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
